version: "3.9"
services:
    mysql:
        image: mysql
        container_name: mysql
        restart: always
        ports:
            - "${MYSQL_PORT}:${MYSQL_PORT}"
        networks:
            - testing-network
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_RANDOM_ROOT_PASSWORD: true
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        ports:
            - "${MONGO_PORT}:${MONGO_PORT}"
        networks:
            - testing-network
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    pg:
        image: postgres
        container_name: pg
        restart: always
        ports:
            - "${POSTGRESS_PORT}:${POSTGRESS_PORT}"
        networks:
            - testing-network
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
networks:
    testing-network:
