# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
    push:
        branches: ["master", "dev", "feature/integration-tests"]
    pull_request:
        branches: ["master", "dev"]
env:
    MYSQL_PORT: 3306
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: root
    MONGO_PORT: 27017
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: root
    MONGO_INITDB_DATABASE: test
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Setup environment
              run: docker compose -f docker-compose.yml up -d
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run lint
            - run: npm run test:all
